# Site settings
title: Matheus Sampaio
author: Matheus Sampaio
email: matheus@sampaio.us
description: > # this means to ignore newlines until "baseurl:"
  About everything.
footer_description: > # this means to ignore newlines until "baseurl:"
  @ 2015 Matheus Sampaio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matheus.sampaio.us" # the base hostname & protocol for your site

twitter_username: matheussampaio
github_username:  matheussampaio
exclude: [vendor]

# Build settings
markdown: kramdown

gems:
  - jemoji
