# Site settings
title_left    : ""
title_right   : "Matheus Sampaio"
description   : "Blog"
keywords      : "node, git, react, vim, zsh"
url           : http://matheus.sampaio.us
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-11435494-5
twitter_username  : "matheussampaio"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false
future            : false
show_drafts       : false

# Build settings
permalink   : /:year/:month/:day/:title
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Matheus Sampaio"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jemoji

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "Dockerfile", "docker-compose.yml", ".env"]
